# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermaritalstatus',
            name='status',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
