# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
