from api.models.contact_info import *
from api.models.education_info import *
from api.models.interest_info import *
from api.models.location_info import *
from api.models.master_company import *
from api.models.master_designation import *
from api.models.master_education_type import *
from api.models.master_interest import *
from api.models.master_location import *
from api.models.master_marital_status import *
from api.models.master_notification_type import *
from api.models.master_post_type import *
from api.models.master_project import *
from api.models.master_public_site import *
from api.models.master_skill import *
from api.models.master_university import *
from api.models.notification import *
from api.models.post import *
from api.models.post_comment import *
from api.models.post_like import *
from api.models.project_info import *
from api.models.public_profile_info import *
from api.models.salary_info import *
from api.models.skill_info import *
from api.models.user import *
from api.models.work_info import *
